config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'articles#index'
  resources :articles do
  	resources :comments
  	resources :reviews
  end
  resources :tags
  resources :authors
  resources :author_sessions, only: [ :new, :create, :destroy ]

get 'login'  => 'author_sessions#new'
get 'logout' => 'author_sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	
	has_many :comments
	has_many :taggings, dependent: :destroy
	has_many :tags, through: :taggings
	has_many :reviews, dependent: :destroy
	has_attached_file :image
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
	
	def tag_list
  		self.tags.collect do |tag|
    	tag.name
  		end.join(", ")
	end
	def tag_list=(tags_string)
  		tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
  		new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
  		self.tags = new_or_found_tags
	end
end

app/models/author.rb
class Author < ApplicationRecord
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match Password", if: :password
  validates_uniqueness_of :email, message: "is already registered!"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :taggings
	has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	include ArticlesHelper
	before_filter :require_login, except: [:index, :show]
	def index
  		@articles = Article.all
	end
	def show
		@article = Article.find(params[:id])
		@comment = Comment.new
		@comment.article_id = @article.id
		@review = Review.new
		@avg = Review.where(:article_id => @article.id).average(:rating)
		@imp = @article.body.summarize(:ratio => 25,:topics => true)
		@review.article_id = @article.id
	end
	def new
		@article = Article.new
	end
	def create
		sites	 = {
			'news18' => '#article_body',
			'indiatimes' => '.section1'
		}
		headings = {
			'news18' => '#page1>h1',
			'indiatimes' => '.header1'
		}
		if article_params['body'][0..3] == 'http'
			url = article_params['body']
			page = HTTParty.get(url)
			parsed_page = Nokogiri::HTML(page)
			sitename = (url.scan(/\.\w+\./))[0][1..-2]
			content = parsed_page.css(sites[sitename])
			content.search('style,div').each do |node| 
  				node.remove
			end
			content = Rails::Html::FullSanitizer.new.sanitize(content.text.gsub(/(?:\n\r?|\r\n?)/, '<br>'))
			imp = content.summarize(:topics => true)
			params[:article][:tag_list] = imp[1].force_encoding(Encoding::UTF_8)
			@article = Article.new(article_params)
			header = parsed_page.css(headings[sitename])
			@article.body = content
			@article.title = Rails::Html::FullSanitizer.new.sanitize(header.text.gsub(/(?:\n\r?|\r\n?)/, '<br>'))
		end
		@article.save
		redirect_to article_path(@article)
	end
	def destroy
		@article = Article.find(params[:id])
		@article.destroy
		redirect_to articles_path
	end
	def edit
		@article = Article.find(params[:id])
	end
	def update
  		@article = Article.find(params[:id])
  		@article.update(article_params)

  		flash.notice = "Article '#{@article.title}' Updated!"
  		redirect_to article_path(@article)
	end
end

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController
  def new
  end

  def create
    if login(params[:email], params[:password])
      redirect_back_or_to(articles_path, notice: 'Logged in successfully.')
    else
      flash.now.alert = "Login failed."
      render action: :new
    end
  end

  def destroy
    logout
    redirect_to(:authors, notice: 'Logged out!')
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
before_filter :require_login, except: [:new, :create]

def zero_authors_or_authenticated
  unless Author.count == 0 || current_user
    redirect_to root_path
    return false
  end
end
  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:username, :email, :password, :password_confirmation)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filter :require_login
	def create
  		@comment = Comment.new(comment_params)
  		@comment.article_id = params[:article_id]

		@comment.save

  		redirect_to article_path(@comment.article)
	end

	def comment_params
  		params.require(:comment).permit(:author_name, :body)
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_filter :require_login
	def create
  		@review = Review.new(review_params)
  		@review.article_id = params[:article_id]
		@review.save

  		redirect_to article_path(@review.article_id)
	end

	def review_params
  		params.require(:review).permit(:rating, :detail)
	end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	before_filter :require_login, only: [:destroy]

def index
	@tags = Tag.all
end
def show
  @tag = Tag.find(params[:id])
end
def destroy
	@tag = Tag.find(params[:id])
	@tag.delete
	redirect_to tags_path
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
	def article_params
  		params.require(:article).permit(:title, :body, :tag_list, :image);
	end
end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.erb
<div class="comment_view">
  <div class="comment_header">
  <h4>Comment by <%= comment.author_name %></h4>
  <p class="comment_time">Posted <%= distance_of_time_in_words(Time.now, comment.created_at) %> ago</p>
  </div>
  <p class="comment"><%= comment.body %></p>
</div>

app/views/articles/_form.html.erb
<div class="create">
<%= form_for(@article, html: {multipart: true}) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title, placeholder: "TITLE" %>
  </p>
  <p>
    <%= f.label :body , class: "articleb" %>
    <%= f.text_area :body %>
  </p>
  <p>
  <%= f.label :tag_list %><br />
  <%= f.text_field :tag_list, placeholder: "TAGS" %>
</p>
<br>
<p>
  <%= f.label :image, "Attach an Image" %><br/>
  <%= f.file_field :image %>
</p>
<br>
  <p>
    <%= f.submit %>
  </p>
<% end %>
</div>

app/views/articles/edit.html.erb
<div class="newa">
<h1>Edit Article</h1>
</div>
<%= render partial: 'form' %>

app/views/articles/index.html.erb
<div class="index">
<h1>All Articles
<% if logged_in? %>
  <%= link_to HTMLEntities.new.decode('&#10010;'), new_article_path, class: "new_btn" %>
<% end %></h1>
<ul id="articles">
  <% @articles.sort_by{|a| a.title}.each do |article| %>
    <li>
    <% @avg = Review.where(:article_id => article.id).average(:rating) %> 
    <div class="article_link row">
      <div class="row">
      <div class="col-sm-2">
      <% if article.image.exists? %>
      	<%= image_tag article.image.url, class: "link_image" %>
      <% else %>
        <img src="/assets/null.gif" class="link_image">
  	  <% end %>
  	 </div>
     <div class="col-sm-6">
      <%= link_to article.title, article_path(article), class: "link_title" %>
    </div>
      <div class="col-sm-4 rating-row">
    <% @avg.to_i.times do %>
      <i class="glyphicon glyphicon-star"></i>
    <% end %>
    <% (5-@avg.to_i).times do %>
      <i class="glyphicon glyphicon-star-empty"></i>
    <% end %>
    	</div>
    </div>
    <div class="article_summary row">
        <%= article.body.summarize(:ratio => 3).force_encoding(Encoding::UTF_8) %>
    </div>
  </div>
    </li>
  <% end %>
</ul>
</div>

app/views/articles/new.html.erb
<div class="newa">
<h1>Create a New Article</h1>
</div>
<%= render partial: 'form' %>

app/views/articles/show.html.erb
<div class="article_page">
<div class="article_head">
<h1><%= @article.title %></h1>
<% if logged_in? %>
<%= link_to "delete", article_path(@article), method: :delete, data: {confirm: "Really delete the article?"}, class: "panel" %>
<%= link_to "edit", edit_article_path(@article), class: "panel" %>
<% end %>
<div class="rating">
Rating :
		<% @avg.to_i.times do %>
			<i class="glyphicon glyphicon-star"></i>
		<% end %>
		<% (5-@avg.to_i).times do %>
			<i class="glyphicon glyphicon-star-empty"></i>
		<% end %>
</div></div>
<p>
  Tags:
  <% @article.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
  <% end %><br>
  Topics:
  <%= @imp[1].force_encoding(Encoding::UTF_8) %>
</p>
<br>
<p>
  <% if @article.image.exists? %>
      <%= image_tag @article.image.url, class: "article_image" %><br/>
  <% end %>
</p>
<p class= "article_content" ><%= @article.body %></p>
</div>
<% if logged_in? %>
<div class = "comments_panel row">
<div class="col-sm-6">
<%= render partial: 'comments/form' %>
</div>
<div class="col-sm-6">
<%= render partial: 'reviews/form' %>
</div>
</div>
<% end %>
<div class="comments_view">
<h3>Comments (<%= @article.comments.size %>)</h3><br>
<%= render partial: 'articles/comment', collection: @article.comments %>
</div>

app/views/author_sessions/new.html.erb
<div class = "login">
<img alt="user_logo" id="user_logo" src="assets/user.png"/>
<h1>Login</h1>
<%= form_tag author_sessions_path, method: :post do %>
  <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email, nil,placeholder: "EMAIL" %>
    <br/>
  </div>
  <br>
  <div class="field">
    <%= label_tag :password %>
    <%= password_field_tag :password, nil, placeholder: "PASSWORD" %>
    <br/>
  </div>
  <br>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>
</div>

app/views/authors/_form.html.erb
<% if author.errors.any? %>
  <div id="error_explanation">
    <ul class= "alert alert-warning">
     <% author.errors.full_messages.each do |message| %>
     <li><%= message %></li>
     <% end %>
    </ul>
  </div>
<% end %>
<%= form_for(author) do |f| %>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username , placeholder: "USERNAME"%>
  </div>
<br>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email ,  placeholder: "EMAIL" %>
  </div>
<br>
<div class="field">
  <%= f.label :password %>
  <%= f.password_field :password, placeholder: "PASSWORD" %>
</div>
<div class="field">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, placeholder: "CONFIRM PASSWORD" %>
</div>
<br>
  <div class="actions">
    <%= f.submit "Signup" %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<div class="signup edit_panel">
<h1>Editing Author</h1>
<%= render 'form', author: @author %>

<%= link_to HTMLEntities.new.decode('&#10006;'), @author ,class: "edit_close_btn"%> |
</div>10006

app/views/authors/index.html.erb
<div class="authors_index">
<h1>Authors</h1>

<table class="table table-striped table-responsive">
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= link_to author.username, author %></td>
        <% if current_user.email == 'akshatd4@gmail.com' %>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>

app/views/authors/new.html.erb
<div class="signup">
<img alt="user_logo" id="user_logo" src="../assets/user.png"/>
<h1>Sign Up</h1>

<%= render 'form', author: @author %>

</div>

app/views/authors/show.html.erb
<div class="authors_view">
<p>
  <strong>Username:</strong>
  <%= @author.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>
	
<% if @author.email == current_user.email || current_user.email == 'akshatd4@gmail.com' %> 
<%= link_to 'Edit', edit_author_path(@author) %> |
<% end %>
<%= link_to 'Back', authors_path %>
</div>

app/views/comments/_form.html.erb
<h2>Post a Comment</h2>

<%= form_for [ @article, @comment ] do |f| %>
  <p>
    <%= f.label :author_name, "Your Name"%>
    <%= f.text_field :author_name,   placeholder: "Your Name"   %>
  </p>
  <br>
  <p>
    <%= f.label :body, "Your Comment"  ,class: "commentb" %>
    <%= f.text_area :body %>
  </p>
  <br>
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

app/views/reviews/_form.html.erb
<h2>Review</h2>

<%= form_for [ @article, @review ] do |f| %>
    <%= f.label :rating, "Rating" , class: "rating-val"%>
    <%= f.radio_button :rating, 1 %>
    <%= f.radio_button :rating, 2 %>
    <%= f.radio_button :rating, 3 %>
    <%= f.radio_button :rating, 4 %>
    <%= f.radio_button :rating, 5 %>
    <br>
    <div class= "rating-bar">
    <i class="rating-star glyphicon glyphicon-star-empty b1"></i>
    <i class="rating-star glyphicon glyphicon-star-empty"></i>
    <i class="rating-star glyphicon glyphicon-star-empty"></i>
    <i class="rating-star glyphicon glyphicon-star-empty"></i>
    <i class="rating-star glyphicon glyphicon-star-empty"></i>
    </div>
  <br>
  <p>
    <%= f.label :detail, "Review"  ,class: "commentb" %>
    <%= f.text_area :detail %>
  </p>
  <br>
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

app/views/tags/index.html.erb
<div class="tag_all">
<h1>All Tags</h1>

<ul id="tags">
  <% @tags.each do |tag| %>
    <li class = "tags">
      <%= link_to tag.name, tag_path(tag) %>
      <%= link_to "delete", tag_path(tag), method: :delete, data: {confirm: "Really delete the article?"}, class: "del_tag" %>
    </li>
  <% end %>
</ul>
</div>

app/views/tags/show.html.erb
<h1 class="tagged">Articles Tagged with <%= @tag.name %></h1>

<ul>
  <% @tag.articles.each do |article| %>
    <li>    <div class="article_link row">
    <div class="col-sm-2">
      <% if article.image.exists? %>
      	<%= image_tag article.image.url, class: "link_image" %>
      <% else %>
        <img src="/assets/null.gif" class="link_image">
  	  <% end %>
  	 </div>
     <div class="col-sm-10">
      <%= link_to article.title, article_path(article), class: "link_title" %>
    	</div>
    </div>
    </li>
  <% end %>
</ul>