config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'articles#index'
  resources :articles do
  	resources :comments
  	resources :reviews
  end
  resources :tags
  resources :authors
  resources :author_sessions, only: [ :new, :create, :destroy ]

get 'login'  => 'author_sessions#new'
get 'logout' => 'author_sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	
	has_many :comments
	has_many :taggings, dependent: :destroy
	has_many :tags, through: :taggings
	has_many :reviews, dependent: :destroy
	has_attached_file :image
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
	
	def tag_list
  		self.tags.collect do |tag|
    	tag.name
  		end.join(", ")
	end
	def tag_list=(tags_string)
  		tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
  		new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
  		self.tags = new_or_found_tags
	end
end

app/models/author.rb
class Author < ApplicationRecord
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match Password", if: :password
  validates_uniqueness_of :email, message: "is already registered!"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :taggings
	has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	include ArticlesHelper
	before_filter :require_login, except: [:index, :show]
	def index
  		@articles = Article.all
	end
	def show
		@article = Article.find(params[:id])
		@comment = Comment.new
		@comment.article_id = @article.id
		@review = Review.new
		@avg = Review.where(:article_id => @article.id).average(:rating)
		@imp = @article.body.summarize(:ratio => 25,:topics => true)
		@review.article_id = @article.id
	end
	def new
		@article = Article.new
	end
	def create
		sites	 = {
			'news18' => '#article_body',
			'indiatimes' => '.section1'
		}
		headings = {
			'news18' => '#page1>h1',
			'indiatimes' => '.header1'
		}
		if article_params['body'][0..3] == 'http'
			url = article_params['body']
			page = HTTParty.get(url)
			parsed_page = Nokogiri::HTML(page)
			sitename = (url.scan(/\.\w+\./))[0][1..-2]
			content = parsed_page.css(sites[sitename])
			content.search('style,div').each do |node| 
  				node.remove
			end
			content = Rails::Html::FullSanitizer.new.sanitize(content.text.gsub(/(?:\n\r?|\r\n?)/, '<br>'))
			imp = content.summarize(:topics => true)
			params[:article][:tag_list] = imp[1].force_encoding(Encoding::UTF_8)
			@article = Article.new(article_params)
			header = parsed_page.css(headings[sitename])
			@article.body = content
			@article.title = Rails::Html::FullSanitizer.new.sanitize(header.text.gsub(/(?:\n\r?|\r\n?)/, '<br>'))
		end
		@article.save
		redirect_to article_path(@article)
	end
	def destroy
		@article = Article.find(params[:id])
		@article.destroy
		redirect_to articles_path
	end
	def edit
		@article = Article.find(params[:id])
	end
	def update
  		@article = Article.find(params[:id])
  		@article.update(article_params)

  		flash.notice = "Article '#{@article.title}' Updated!"
  		redirect_to article_path(@article)
	end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
before_filter :require_login, except: [:new, :create]

def zero_authors_or_authenticated
  unless Author.count == 0 || current_user
    redirect_to root_path
    return false
  end
end
  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:username, :email, :password, :password_confirmation)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filter :require_login
	def create
  		@comment = Comment.new(comment_params)
  		@comment.article_id = params[:article_id]

		@comment.save

  		redirect_to article_path(@comment.article)
	end

	def comment_params
  		params.require(:comment).permit(:author_name, :body)
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_filter :require_login
	def create
  		@review = Review.new(review_params)
  		@review.article_id = params[:article_id]
		@review.save

  		redirect_to article_path(@review.article_id)
	end

	def review_params
  		params.require(:review).permit(:rating, :detail)
	end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	before_filter :require_login, only: [:destroy]

def index
	@tags = Tag.all
end
def show
  @tag = Tag.find(params[:id])
end
def destroy
	@tag = Tag.find(params[:id])
	@tag.delete
	redirect_to tags_path
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
	def article_params
  		params.require(:article).permit(:title, :body, :tag_list, :image);
	end
end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link rel="icon" href="/assets/Logo.png">
<meta name="theme-color" content="#4285f4">
<meta name="msapplication-navbutton-color" content="#4285f4">
  <meta charset="UTF-8">
  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="/assets/Logo.png"/>
    <title>Blogdb</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <div class="loader"><center><%= image_tag "page-loader.gif" %></center></div>
  <nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
      <a class="navbar-brand" href="/articles"><%= image_tag "header.png", class: "header_img" %></a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
    <ul class="nav navbar-nav">
      <li><a href="/articles">Home</a></li>
      <% if logged_in?  %>
        <li><a href="/authors">Authors</a></li>
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
    <% if logged_in? %>
      <li><%= link_to "#{current_user.username}", author_path(current_user.id) %></li>
      <li><%= link_to "Logout", logout_path %></li>
    <% else %>
      <li><%= link_to "Signup", new_author_path %></li>
      <li><%= link_to "Login", login_path %></li>
    <% end %>
    </ul>
    </div>
  </div>
</nav>
  <div class="container">
  <div class="pad"></div>
    <div class="row"><p class="flash">
    <% flash.each do |key, msg| %>
  <%= content_tag :div, msg, class: "alert alert-success" %>
<% end %>
  </p></div>
    <div class="row">
    <div class="col-sm-12">
      <%= yield %>
    </div>
    </div>
  </div>    
  </body>
</html>